### ISSUE TITLE
Scenario

### ISSUE THREAD

**Issue by cyb3rsalih** [hakluke/bug-bounty-standards#1]
Hacker submits a bug but closed as duplicate. But after the old report closed as resolved, duplicated report still reproducible. 

Resolution: Disclosed report status should changed to triage and, the program should pay the relevant bounty.

**Comment by hakluke** [comment]
The current policy for Bugcrowd - and I believe also Hackerone, is that once a report is marked as resolved, it can be resubmitted if it still exists. I think the existing policy is probably fine.

**Comment by cyb3rsalih** [comment]
Sorry,  maybe I can't tell well the situation. Most of programs doesn't notify the duplicated report. So original report get rewarded and duplicated one still stays duplicate.

**Comment by hakluke** [comment]
In both Bugcrowd and Hackerone when the original report is marked as resolved, the duplicate bug is also updated to resolved automatically.

**Comment by cyb3rsalih** [comment]
Thanks.
