### ISSUE TITLE
Variant of ID 8: Acquisition

### ISSUE THREAD

**Issue by jhaddix** [hakluke/bug-bounty-standards#2]
Hacker submits a bug to a program that has an open scope brief. The bug is on an acquisition. The program owner does not control the IT infrastructure or staff of the acquisition. 

Resolution: The program owner should make a good faith effort, verified by the platform, to inform the acquisition. Should the acquisition benefit from the submission, the program owner should pay the bounty. The brief should be updated to reflect if acquisition(s) are in scope.

**Comment by hakluke** [comment]
Totally agree! I think maybe a good action item for platforms would be to have a visible binary switch on programs. Are acquisitions in scope Y/N. Do you think that would solve it?

**Comment by hakluke** [comment]
Added
